=== priyankayadav98/lease-management-system/dom.xsd
<?xml version="1.0" encoding="UTF-8"?>
<em:schema xmlns:em ="http://www.w3.org/2001/XMLSchema">
	<em:element name="Rental" type="Tenants" />
    <em:complexType name="Tenants">
      <em:sequence>
         <em:element name="Tenant" type="tmp" minOccurs="1" maxOccurs="unbounded" />	
      </em:sequence>
    </em:complexType>
    
    <em:complexType name="tmp">
      <em:sequence>
         <em:element name="Name" type="em:string" />
         <em:element name="Age" type="em:integer" />
         <em:element name="NO_MEMBER" type="em:integer" />
         <em:element name="Phonenum" type="check" />
      </em:sequence>
      <em:attribute name="ID" type="em:ID" use="required" />
      
      
    </em:complexType>
    
     <em:simpleType name = "check">
           <em:restriction base = "em:integer">
           <em:totalDigits value = "10"></em:totalDigits>
           </em:restriction>
           </em:simpleType>
           </em:schema>

=== priyankayadav98/lease-management-system/tenant.xml
<?xml version="1.0" encoding="UTF-8"?>
<Rental xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="dom.xsd">
  <Tenant ID="101">
    <Name>Vishnu</Name>
    <Age>23</Age>
    <NO_MEMBER>3</NO_MEMBER>
    <Phonenum>6289676192</Phonenum>
  </Tenant>
  <Tenant ID="102">
    <Name>Vimal</Name>
    <Age>32</Age>
    <NO_MEMBER>2</NO_MEMBER>
    <Phonenum>6289676292</Phonenum>
  </Tenant>
   <Tenant ID="103">
    <Name>Vikash</Name>
    <Age>21</Age>
    <NO_MEMBER>1</NO_MEMBER>
    <Phonenum>6289676392</Phonenum>
  </Tenant>
  <Tenant ID="104">
    <Name>Pradeep</Name>
    <Age>20</Age>
    <NO_MEMBER>4</NO_MEMBER>
    <Phonenum>6289676492</Phonenum>
  </Tenant>
  <Tenant ID="105">
    <Name>Amina</Name>
    <Age>45</Age>
    <NO_MEMBER>5</NO_MEMBER>
    <Phonenum>6289676592</Phonenum>
  </Tenant>
</Rental>
