=== priyankayadav98/lease-management-system/rental_demo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<rm:schema xmlns:rm="http://www.w3.org/2001/XMLSchema">
<rm:element name = "rental">
   <rm:complexType>
      <rm:sequence>
         <rm:element name = "Tenant" maxOccurs = "unbounded">
   <rm:complexType>
      <rm:sequence>
         <rm:element name ="Name" type = "rm:string">
            </rm:element>
         <rm:element name ="Age" type = "myage">
            </rm:element>
         <rm:element name ="NO_MEMBER" type = "rm:integer">
           </rm:element>
           <rm:element name ="ID" type = "check">
           </rm:element>
           
        
           
           </rm:sequence>
           </rm:complexType>
           </rm:element>
           
 
         <rm:element name = "Owner" maxOccurs = "unbounded">
  <rm:complexType>
     <rm:sequence>
        <rm:element name = "Name" type = "rm:string">
          </rm:element>
        <rm:element name = "No_building" type = "rm:integer">
          </rm:element>
        <rm:element name = "ID" type ="check">
          </rm:element>
          
          </rm:sequence>
           </rm:complexType>
           </rm:element>
           
         <rm:element name = "BUILDING" maxOccurs = "unbounded">
  <rm:complexType>
     <rm:sequence>
        <rm:element name = "House_No" type = "check">
          </rm:element>
        <rm:element name = "Type" type = "rm:string">
          </rm:element>
        <rm:element name = "Area" type ="rm:string">
          </rm:element>
          
          </rm:sequence>
           </rm:complexType>
           </rm:element>
          
         <rm:element name = "FURNISHING" maxOccurs = "unbounded">
  <rm:complexType>
     <rm:sequence>
        <rm:element name = "Type" type = "rm:string">
          </rm:element>
        <rm:element name = "No_pieces" type = "rm:integer">
          </rm:element>
        <rm:element name = "date" type ="rm:date">
          </rm:element>


	</rm:sequence>
           </rm:complexType>
           </rm:element> 
           
                    
         <rm:element name = "Contract" maxOccurs = "unbounded">
  <rm:complexType>
     <rm:sequence>
        <rm:element name = "ID" type = "rm:integer">
          </rm:element>
        <rm:element name = "Years" type = "rm:integer">
          </rm:element>
        <rm:element name = "Do_registration" type ="rm:date">
          </rm:element>
          <rm:element name = "Security" type ="rm:float">
          </rm:element>
          
          </rm:sequence>
           </rm:complexType>
           </rm:element>
          
          <rm:element name = "TRANSACTION" maxOccurs = "unbounded">
  <rm:complexType>
     <rm:sequence>
        <rm:element name = "Type" type = "rm:string">
          </rm:element>
        <rm:element name = "PAYMENT_ID" type = "rm:integer">
          </rm:element>
        <rm:element name = "Date" type ="rm:date">
          </rm:element>
          <rm:element name = "Dues" type ="rm:integer">
          </rm:element>
          
          </rm:sequence>
           </rm:complexType>
           </rm:element>
          
          <rm:element name = "TENANT_OUT" maxOccurs = "unbounded">
  <rm:complexType>
     <rm:sequence>
        <rm:element name = "Date_checkout" type = "rm:date">
          </rm:element>
        <rm:element name = "feedback" type = "rm:string">
          </rm:element>
        <rm:element name = "status" type ="rm:string">
          </rm:element>
     </rm:sequence>
 </rm:complexType>
          </rm:element>
           </rm:sequence>
           </rm:complexType>
           </rm:element>
           <rm:simpleType name = "myage">
           <rm:restriction base =  "rm:integer">
           <rm:minInclusive value="18"></rm:minInclusive>
           </rm:restriction>
           </rm:simpleType>
           
           <rm:simpleType name = "check">
           <rm:restriction base = "rm:integer">
           <rm:totalDigits value = "5"></rm:totalDigits>
           </rm:restriction>
           </rm:simpleType>
           
            
           
           
           </rm:schema>

=== priyankayadav98/lease-management-system/NewFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="style.xsl" ?>
<rental xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="rental_demo.xsd">
  
  <Tenant>
    <Name>ANKUR</Name>
    <Age>23</Age>
    <NO_MEMBER>5</NO_MEMBER>
    <ID>12345</ID>
  </Tenant>
  <Tenant>
    <Name>AYUSHREE</Name>
    <Age>18</Age>
    <NO_MEMBER>3</NO_MEMBER>
    <ID>12678</ID>
  </Tenant>
  <Tenant>
    <Name>ADARSH</Name>
    <Age>21</Age>
    <NO_MEMBER>4</NO_MEMBER>
    <ID>18653</ID>
  </Tenant>
  <Tenant>
    <Name>DIVYA</Name>
    <Age>18</Age>
    <NO_MEMBER>6</NO_MEMBER>
    <ID>17654</ID>
  </Tenant>
  <Tenant>
    <Name>RUEBEN</Name>
    <Age>19</Age>
    <NO_MEMBER>3</NO_MEMBER>
    <ID>12453</ID>
  </Tenant>
  <Tenant>
    <Name>ASHWIN</Name>
    <Age>21</Age>
    <NO_MEMBER>2</NO_MEMBER>
    <ID>12517</ID>
  </Tenant>
  
  <Owner>
    <Name>PRADEEP</Name>
    <No_building>8</No_building>
    <ID>23457</ID>
  </Owner>
  
  <Owner>
    <Name>AMBER</Name>
    <No_building>4</No_building>
    <ID>24562</ID>
  </Owner>
  
  <Owner>
    <Name>PRANEET</Name>
    <No_building>4</No_building>
    <ID>24572</ID>
  </Owner>
  
  <Owner>
    <Name>ANANYA</Name>
    <No_building>3</No_building>
    <ID>27890</ID>
  </Owner>
  
  <Owner>
    <Name>VIPUL</Name>
    <No_building>5</No_building>
    <ID>21567</ID>
  </Owner>
  
  <Owner>
    <Name>SHIPRA</Name>
    <No_building>7</No_building>
    <ID>20981</ID>
  </Owner>
  <BUILDING>
    <House_No>123</House_No>
    <Type>VILLA</Type>
    <Area>JP NAGAR</Area>
  </BUILDING>
  <BUILDING>
    <House_No>234</House_No>
    <Type>FLAT</Type>
    <Area>SG PALAYA</Area>
  </BUILDING>
  <BUILDING>
    <House_No>240</House_No>
    <Type>VILLA</Type>
    <Area>JAYNAGAR</Area>
  </BUILDING>
  <BUILDING>
    <House_No>213</House_No>
    <Type>VILLA</Type>
    <Area>KHARAGPUR</Area>
  </BUILDING>
  <BUILDING>
    <House_No>245</House_No>
    <Type>FLAT</Type>
    <Area>SILIGURI</Area>
  </BUILDING>
  <BUILDING>
    <House_No>261</House_No>
    <Type>FLAT</Type>
    <Area>SALT LAKE</Area>
  </BUILDING>
  <FURNISHING>
    <Type>MASTER BEDROOM</Type>
    <No_pieces>3</No_pieces>
    <date>2013-01-01</date>
  </FURNISHING>	
  <FURNISHING>
    <Type>BATHROOM</Type>
    <No_pieces>2</No_pieces>
    <date>2004-01-05</date>
  </FURNISHING>
  <FURNISHING>
    <Type>KITCHEN</Type>
    <No_pieces>4</No_pieces>
    <date>2016-07-11</date>
  </FURNISHING>
  <FURNISHING>
    <Type>DINING</Type>
    <No_pieces>2</No_pieces>
    <date>2020-12-04</date>
  </FURNISHING>
  <FURNISHING>
    <Type>LIVING</Type>
    <No_pieces>6</No_pieces>
    <date>2014-11-07</date>
  </FURNISHING>
  <FURNISHING>
    <Type>KID ROOM</Type>
    <No_pieces>7</No_pieces>
    <date>2018-09-16</date>
  </FURNISHING>
  <Contract>
    <ID>89898</ID>
    <Years>1</Years>
    <Do_registration>2010-01-11</Do_registration>
    <Security>2000</Security>
  </Contract>
  <Contract>
    <ID>87699</ID>
    <Years>5</Years>
    <Do_registration>2016-01-10</Do_registration>
    <Security>1000</Security>
  </Contract>
  <Contract>
    <ID>77878</ID>
    <Years>1</Years>
    <Do_registration>2011-01-10</Do_registration>
    <Security>10000</Security>
  </Contract>
  <Contract>
    <ID>59899</ID>
    <Years>3</Years>
    <Do_registration>2004-05-01</Do_registration>
    <Security>5000</Security>
  </Contract>
  <Contract>
    <ID>90899</ID>
    <Years>2</Years>
    <Do_registration>2013-11-01</Do_registration>
    <Security>6000</Security>
  </Contract>
  <Contract>
    <ID>242451</ID>
    <Years>5</Years>
    <Do_registration>2014-12-01</Do_registration>
    <Security>7000</Security>
  </Contract>
  <TRANSACTION>
    <Type>Cash</Type>
    <PAYMENT_ID>12345</PAYMENT_ID>
    <Date>2011-11-01</Date>
    <Dues>200</Dues>
  </TRANSACTION>
  <TRANSACTION>
    <Type>EMI</Type>
    <PAYMENT_ID>12891</PAYMENT_ID>
    <Date>2018-01-23</Date>
    <Dues>0</Dues>
  </TRANSACTION>
  <TRANSACTION>
    <Type>CASH</Type>
    <PAYMENT_ID>14568</PAYMENT_ID>
    <Date>2013-12-01</Date>
    <Dues>10000</Dues>
  </TRANSACTION>
  <TRANSACTION>
    <Type>EMI</Type>
    <PAYMENT_ID>0</PAYMENT_ID>
    <Date>2012-05-09</Date>
    <Dues>0</Dues>
  </TRANSACTION>
  <TRANSACTION>
    <Type>CASH</Type>
    <PAYMENT_ID>34366</PAYMENT_ID>
    <Date>2009-11-01</Date>
    <Dues>0</Dues>
  </TRANSACTION>
  <TRANSACTION>
    <Type>CASH</Type>
    <PAYMENT_ID>98909</PAYMENT_ID>
    <Date>2021-01-01</Date>
    <Dues>4000</Dues>
  </TRANSACTION>
  <TENANT_OUT>
    <Date_checkout>2012-01-11</Date_checkout>
    <feedback>GOOD</feedback>
    <status>OK</status>
  </TENANT_OUT>
   <TENANT_OUT>
    <Date_checkout>2015-12-11</Date_checkout>
    <feedback>FAIR</feedback>
    <status>FINED</status>
  </TENANT_OUT>
   <TENANT_OUT>
    <Date_checkout>2016-09-21</Date_checkout>
    <feedback>SATTISFACTORY</feedback>
    <status>OK</status>
  </TENANT_OUT>
   <TENANT_OUT>
    <Date_checkout>2009-04-14</Date_checkout>
    <feedback>GOOD</feedback>
    <status>OK</status>
  </TENANT_OUT>
   <TENANT_OUT>
    <Date_checkout>2016-09-19</Date_checkout>
    <feedback>BAD</feedback>
    <status>FINED</status>
  </TENANT_OUT>
   <TENANT_OUT>
    <Date_checkout>2021-08-31</Date_checkout>
    <feedback>FINE</feedback>
    <status>OK</status>
  </TENANT_OUT>
</rental>
